[package]
name = "playpen"
version = "0.3.1"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
atty = "0.2.14"
clap = { version = "4", features = ["derive"] }
nix = { version = "0.29", features = ["process"] }

[dev-dependencies]
tempfile = "3"
assert_cmd = "2"
predicates = "3"
